CREATE TABLE TEAM(
    TEAM_ID VARCHAR2(10), 
    TEAM_LOCATION VARCHAR2(10), 
    TEAM_NAME VARCHAR2(20), 
    TEAM_DATE DATE, 
    PHONENUMBER VARCHAR2(12),
    HOMEPAGE VARCHAR2(50),
    CONSTRAINT PK_TEAM PRIMARY KEY(TEAM_ID)
);


CREATE TABLE PLAYER(
    PLAYER_NUMBER INTEGER,
    PLAYER_NAME VARCHAR2(20),
    PLAYER_DATE DATE,
    PLAYER_POSITION VARCHAR(10),
    PLAYER_HEIGHT NUMBER(5, 2),
    TEAM_ID VARCHAR2(10),
    CONSTRAINT FK_PLAYER FOREIGN KEY(TEAM_ID)
        REFERENCES TEAM(TEAM_ID),
    CONSTRAINT PK_PLAYER PRIMARY KEY(PLAYER_NUMBER)
);

DROP TABLE TEAM
CASCADE CONSTRAINTS;

DROP TABLE PLAYER
CASCADE CONSTRAINTS;

INSERT INTO TEAM(TEAM_ID, TEAM_LOCATION, TEAM_NAME, TEAM_DATE, PHONENUMBER, HOMEPAGE)
VALUES('001', '서울', '레드', '21/11/11', '123-4567', 'www.redteam.com');

INSERT INTO TEAM(TEAM_ID, TEAM_LOCATION, TEAM_NAME, TEAM_DATE, PHONENUMBER, HOMEPAGE)
VALUES('002', '경기', '블루', '21/12/12', '234-5678', 'www.blueteam.com');

INSERT INTO PLAYER(PLAYER_NUMBER, PLAYER_NAME, PLAYER_DATE, PLAYER_POSITION, PLAYER_HEIGHT, TEAM_ID)
VALUES(10, '레드일', '21/11/12', '탑', 170.12, '001');

INSERT INTO PLAYER(PLAYER_NUMBER, PLAYER_NAME, PLAYER_DATE, PLAYER_POSITION, PLAYER_HEIGHT, TEAM_ID)
VALUES(11, '레드이', '21/11/13', '미드', 175.16, '001');

INSERT INTO PLAYER(PLAYER_NUMBER, PLAYER_NAME, PLAYER_DATE, PLAYER_POSITION, PLAYER_HEIGHT, TEAM_ID)
VALUES(12, '레드삼', '21/11/14', '바텀', 168.42, '001');

INSERT INTO PLAYER(PLAYER_NUMBER, PLAYER_NAME, PLAYER_DATE, PLAYER_POSITION, PLAYER_HEIGHT, TEAM_ID)
VALUES(21, '블루일', '21/12/20', '탑', 180.02, '002');

INSERT INTO PLAYER(PLAYER_NUMBER, PLAYER_NAME, PLAYER_DATE, PLAYER_POSITION, PLAYER_HEIGHT, TEAM_ID)
VALUES(22, '블루이', '21/12/21', '미드', 175.68, '002');

INSERT INTO PLAYER(PLAYER_NUMBER, PLAYER_NAME, PLAYER_DATE, PLAYER_POSITION, PLAYER_HEIGHT, TEAM_ID)
VALUES(23, '블루삼', '21/12/22', '바텀', 166.22, '002');


select TEAM_NAME, PHONENUMBER, HOMEPAGE
from TEAM, PLAYER
where player.PLAYER_NAME = '블루이' AND player.TEAM_ID = team.TEAM_ID;