CREATE TABLE PRODUCT(
    ITEM_NO INTEGER, 
    ITEM_NAME VARCHAR2(10), 
    PRICE INTEGER, 
    MEMO VARCHAR2(100), 
    CONSTRAINT PK_PRODUCT PRIMARY KEY(ITEM_NO)
);

CREATE TABLE CONSUMER(
    CONSUMER_ID VARCHAR2(10), 
    CONSUMER_NAME VARCHAR2(10), 
    AGE INTEGER, 
    CONSTRAINT PK_CONSUMER PRIMARY KEY(CONSUMER_ID)
);

CREATE SEQUENCE CART_IDX
INCREMENT BY 1  -- 1씩 증가
START WITH 1   -- 시작 숫자
MAXVALUE 100
MINVALUE 1;

DROP SEQUENCE CART_IDX;

DROP TABLE CART
CASCADE CONSTRAINTS;

CREATE TABLE CART(
    CART_NO INTEGER, 
    CONSUMER_ID VARCHAR2(10), 
    ITEM_NO INTEGER, 
    ITEM_COUNT INTEGER, 
    CONSTRAINT FK_CONSUMER_ID FOREIGN KEY(CONSUMER_ID)
        REFERENCES CONSUMER(CONSUMER_ID),
    CONSTRAINT FK_ITEM_NO FOREIGN KEY(ITEM_NO)
        REFERENCES PRODUCT(ITEM_NO),
    CONSTRAINT PK_CART PRIMARY KEY(CART_NO)
);

INSERT INTO PRODUCT(ITEM_NO, ITEM_NAME, PRICE, MEMO)
VALUES(1, '연필', 300, '2B연필');

INSERT INTO PRODUCT(ITEM_NO, ITEM_NAME, PRICE, MEMO)
VALUES(2, '지우개', 500, '검은색 지우개');

INSERT INTO PRODUCT(ITEM_NO, ITEM_NAME, PRICE, MEMO)
VALUES(3, '공책', 2000, '스프링이 달려있습니다.');

INSERT INTO PRODUCT(ITEM_NO, ITEM_NAME, PRICE, MEMO)
VALUES(4, '볼펜', 1000, '검정, 빨강, 파랑의 색이 같이 있습니다.');

INSERT INTO PRODUCT(ITEM_NO, ITEM_NAME, PRICE, MEMO)
VALUES(5, '필통', 5000, '다양한 수납공간을 가집니다.');

INSERT INTO CONSUMER(CONSUMER_ID, CONSUMER_NAME, AGE)
VALUES('STUDENT_1', '학생일', 17);

INSERT INTO CONSUMER(CONSUMER_ID, CONSUMER_NAME, AGE)
VALUES('STUDENT_2', '학생이', 15);

INSERT INTO CART( CART_NO, CONSUMER_ID,ITEM_NO, ITEM_COUNT)
VALUES(CART_IDX.NEXTVAL, 'STUDENT_1', 1, 2);

INSERT INTO CART( CART_NO, CONSUMER_ID,ITEM_NO, ITEM_COUNT)
VALUES(CART_IDX.NEXTVAL, 'STUDENT_1', 2, 1);

SELECT c.CONSUMER_NAME, p.ITEM_NAME, r.ITEM_COUNT
FROM PRODUCT p, CONSUMER c, CART r
    WHERE
    (p.ITEM_NO, r.ITEM_COUNT) IN
    (SELECT ITEM_NO, ITEM_COUNT FROM CART WHERE CONSUMER_ID = 'STUDENT_1')
    AND
    c.consumer_id = 'STUDENT_1';