CREATE TABLE TEAM(
    "팀 아이디" VARCHAR2(10), 
    "지역" VARCHAR2(10), 
    "팀 명" VARCHAR2(20), 
    "개설 날짜" DATE, 
    전화번호 VARCHAR2(12),
    홈페이지 VARCHAR2(50),
    CONSTRAINT PK_TEAM PRIMARY KEY("팀 아이디")
);


CREATE TABLE PLAYER(
    선수번호 INTEGER,
    "선수 명" VARCHAR2(20),
    등록일 DATE,
    포지션 VARCHAR(10),
    키 NUMBER(5, 2),
    "팀 아이디" VARCHAR2(10),
    CONSTRAINT FK_PLAYER FOREIGN KEY("팀 아이디")
        REFERENCES TEAM("팀 아이디"),
    CONSTRAINT PK_PLAYER PRIMARY KEY(선수번호)
);

DROP TABLE TEAM
CASCADE CONSTRAINTS;

DROP TABLE PLAYER
CASCADE CONSTRAINTS;

    
INSERT INTO TEAM("팀 아이디", 지역, "팀 명", "개설 날짜", 전화번호, 홈페이지)
VALUES('001', '서울', '레드', '21/11/11', '123-4567', 'www.redteam.com');

INSERT INTO TEAM("팀 아이디", 지역, "팀 명", "개설 날짜", 전화번호, 홈페이지)
VALUES('002', '경기', '블루', '21/12/12', '234-5678', 'www.blueteam.com');

INSERT INTO PLAYER(선수번호, "선수 명", 등록일, 포지션, 키, "팀 아이디")
VALUES(10, '레드일', '21/11/12', '탑', 170.12, '001');

INSERT INTO PLAYER(선수번호, "선수 명", 등록일, 포지션, 키, "팀 아이디")
VALUES(11, '레드이', '21/11/13', '미드', 175.16, '001');

INSERT INTO PLAYER(선수번호, "선수 명", 등록일, 포지션, 키, "팀 아이디")
VALUES(12, '레드삼', '21/11/14', '바텀', 168.42, '001');

INSERT INTO PLAYER(선수번호, "선수 명", 등록일, 포지션, 키, "팀 아이디")
VALUES(21, '블루일', '21/12/20', '탑', 180.02, '002');

INSERT INTO PLAYER(선수번호, "선수 명", 등록일, 포지션, 키, "팀 아이디")
VALUES(22, '블루이', '21/12/21', '미드', 175.68, '002');

INSERT INTO PLAYER(선수번호, "선수 명", 등록일, 포지션, 키, "팀 아이디")
VALUES(23, '블루삼', '21/12/22', '바텀', 166.22, '002');

select "팀 명", 전화번호, 홈페이지
from TEAM, PLAYER
where player."선수 명" = '블루이' AND player."팀 아이디" = team."팀 아이디";



CREATE TABLE PRODUCT(
    ITEM_NO INTEGER, 
    ITEM_NAME VARCHAR2(10), 
    PRICE INTEGER, 
    MEMO VARCHAR2(100), 
    CONSTRAINT PK_PRODUCT PRIMARY KEY(ITEM_NO)
);

CREATE TABLE CONSUMER(
    CONSUMER_ID VARCHAR2(10), 
    CONSUMER_NAME VARCHAR2(10), 
    AGE INTEGER, 
    CONSTRAINT PK_CONSUMER PRIMARY KEY(CONSUMER_ID)
);

CREATE SEQUENCE CART_IDX
INCREMENT BY 1  -- 1씩 증가
START WITH 1   -- 시작 숫자
MAXVALUE 100
MINVALUE 1;

DROP SEQUENCE CART_IDX;

DROP TABLE CART
CASCADE CONSTRAINTS;

CREATE TABLE CART(
    CART_NO INTEGER, 
    CONSUMER_ID VARCHAR2(10), 
    ITEM_NO INTEGER, 
    ITEM_COUNT INTEGER, 
    CONSTRAINT FK_CONSUMER_ID FOREIGN KEY(CONSUMER_ID)
        REFERENCES CONSUMER(CONSUMER_ID),
    CONSTRAINT FK_ITEM_NO FOREIGN KEY(ITEM_NO)
        REFERENCES PRODUCT(ITEM_NO),
    CONSTRAINT PK_CART PRIMARY KEY(CART_NO)
);

INSERT INTO PRODUCT(ITEM_NO, ITEM_NAME, PRICE, MEMO)
VALUES(1, '연필', 300, '2B연필');

INSERT INTO PRODUCT(ITEM_NO, ITEM_NAME, PRICE, MEMO)
VALUES(2, '지우개', 500, '검은색 지우개');

INSERT INTO PRODUCT(ITEM_NO, ITEM_NAME, PRICE, MEMO)
VALUES(3, '공책', 2000, '스프링이 달려있습니다.');

INSERT INTO PRODUCT(ITEM_NO, ITEM_NAME, PRICE, MEMO)
VALUES(4, '볼펜', 1000, '검정, 빨강, 파랑의 색이 같이 있습니다.');

INSERT INTO PRODUCT(ITEM_NO, ITEM_NAME, PRICE, MEMO)
VALUES(5, '필통', 5000, '다양한 수납공간을 가집니다.');

INSERT INTO CONSUMER(CONSUMER_ID, CONSUMER_NAME, AGE)
VALUES('STUDENT_1', '학생일', 17);

INSERT INTO CONSUMER(CONSUMER_ID, CONSUMER_NAME, AGE)
VALUES('STUDENT_2', '학생이', 15);

INSERT INTO CART( CART_NO, CONSUMER_ID,ITEM_NO, ITEM_COUNT)
VALUES(CART_IDX.NEXTVAL, 'STUDENT_1', 1, 2);

INSERT INTO CART( CART_NO, CONSUMER_ID,ITEM_NO, ITEM_COUNT)
VALUES(CART_IDX.NEXTVAL, 'STUDENT_1', 2, 1);

SELECT c.CONSUMER_NAME, p.ITEM_NAME, r.ITEM_COUNT
FROM PRODUCT p, CONSUMER c, CART r
    WHERE
    (p.ITEM_NO, r.ITEM_COUNT) IN
    (SELECT ITEM_NO, ITEM_COUNT FROM CART WHERE CONSUMER_ID = 'STUDENT_1')
    AND
    c.consumer_id = 'STUDENT_1';
    
SELECT c.CONSUMER_NAME, p.ITEM_NAME, r.ITEM_COUNT
FROM PRODUCT p, CONSUMER c, CART r
WHERE
c.consumer_id = 'STUDENT_1'
AND
r.item_no = p.item_no;